# Generated by Django 4.0.1 on 2024-03-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_transfer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
